In [80]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
# имитирует эстетику ggplot (популярного графического пакета для R
plt.style.use('ggplot')
%matplotlib inline

In [84]:
dataset = pd.read_excel('https://docs.google.com/spreadsheets/d/1gZ2VJcqTpQyd1mqON2BiTahkA39P-TEe/export?format=xlsx&id=1gZ2VJcqTpQyd1mqON2BiTahkA39P-TEe')

In [85]:
dataset

Год  ...  Рентабельность проданных товаров, продукции, работ, услуг
0   1995.0  ...                                               15.8        
1   1996.0  ...                                                4.8        
2   1997.0  ...                                                6.3        
3   1998.0  ...                                                8.1        
4   1999.0  ...                                               18.5        
5   2000.0  ...                                               18.9        
6   2001.0  ...                                               14.4        
7   2002.0  ...                                               10.9        
8   2003.0  ...                                               10.2        
9   2004.0  ...                                               13.2        
10  2005.0  ...                                               13.5        
11  2006.0  ...                                               13.2        
12  2007.0  ...                                               13.1        
13  2008.0  ...                                               13.0        
14  2009.0  ...                                               10.8        
15  2010.0  ...                                               10.0        
16  2011.0  ...                                                9.6        
17  2012.0  ...                                                8.6        
18  2013.0  ...                                                7.0        
19  2014.0  ...                                                7.3        
20  2015.0  ...                                                8.1        
21  2016.0  ...                                                7.6        
22  2017.0  ...                                                6.7        
23  2018.0  ...                                               10.7        
24  2019.0  ...                                               10.8        
25  2020.0  ...                                                9.9        

[26 rows x 4 columns]

In [87]:
c_dataset = dataset[['Рентабельность активов']]

In [88]:
c_dataset

Рентабельность активов
0                      5.3
1                      1.3
2                      1.7
3                     -0.9
4                      5.0
5                      7.6
6                      6.1
7                      4.3
8                      5.9
9                      8.5
10                     8.8
11                    12.2
12                    10.4
13                     5.4
14                     5.5
15                     6.7
16                     6.5
17                     6.1
18                     4.5
19                     2.5
20                     3.7
21                     5.9
22                     3.8
23                     4.7
24                     5.8
25                     4.5

In [89]:
np_c_dataset = np.array(c_dataset)

In [90]:
np_c_dataset

array([[ 5.3],
       [ 1.3],
       [ 1.7],
       [-0.9],
       [ 5. ],
       [ 7.6],
       [ 6.1],
       [ 4.3],
       [ 5.9],
       [ 8.5],
       [ 8.8],
       [12.2],
       [10.4],
       [ 5.4],
       [ 5.5],
       [ 6.7],
       [ 6.5],
       [ 6.1],
       [ 4.5],
       [ 2.5],
       [ 3.7],
       [ 5.9],
       [ 3.8],
       [ 4.7],
       [ 5.8],
       [ 4.5]])

In [91]:
np_dataset = np.array(dataset)

In [92]:
np_dataset


array([[ 1.995e+03,        nan,  5.300e+00,  1.580e+01],
       [ 1.996e+03,        nan,  1.300e+00,  4.800e+00],
       [ 1.997e+03,        nan,  1.700e+00,  6.300e+00],
       [ 1.998e+03,        nan, -9.000e-01,  8.100e+00],
       [ 1.999e+03,        nan,  5.000e+00,  1.850e+01],
       [ 2.000e+03,        nan,  7.600e+00,  1.890e+01],
       [ 2.001e+03,        nan,  6.100e+00,  1.440e+01],
       [ 2.002e+03,        nan,  4.300e+00,  1.090e+01],
       [ 2.003e+03,        nan,  5.900e+00,  1.020e+01],
       [ 2.004e+03,        nan,  8.500e+00,  1.320e+01],
       [ 2.005e+03,        nan,  8.800e+00,  1.350e+01],
       [ 2.006e+03,        nan,  1.220e+01,  1.320e+01],
       [ 2.007e+03,        nan,  1.040e+01,  1.310e+01],
       [ 2.008e+03,        nan,  5.400e+00,  1.300e+01],
       [ 2.009e+03,        nan,  5.500e+00,  1.080e+01],
       [ 2.010e+03,        nan,  6.700e+00,  1.000e+01],
       [ 2.011e+03,        nan,  6.500e+00,  9.600e+00],
       [ 2.012e+03,        nan,

In [93]:
np_f_dataset = np_dataset[:,2] #https://pythonworld.ru/numpy/2.html

In [94]:
np_f_dataset

array([ 5.3,  1.3,  1.7, -0.9,  5. ,  7.6,  6.1,  4.3,  5.9,  8.5,  8.8,
       12.2, 10.4,  5.4,  5.5,  6.7,  6.5,  6.1,  4.5,  2.5,  3.7,  5.9,
        3.8,  4.7,  5.8,  4.5])

In [95]:
np_c_dataset.reshape(-1, 1)

array([[ 5.3],
       [ 1.3],
       [ 1.7],
       [-0.9],
       [ 5. ],
       [ 7.6],
       [ 6.1],
       [ 4.3],
       [ 5.9],
       [ 8.5],
       [ 8.8],
       [12.2],
       [10.4],
       [ 5.4],
       [ 5.5],
       [ 6.7],
       [ 6.5],
       [ 6.1],
       [ 4.5],
       [ 2.5],
       [ 3.7],
       [ 5.9],
       [ 3.8],
       [ 4.7],
       [ 5.8],
       [ 4.5]])

In [96]:
np_f_dataset.reshape(-1, 1)

array([[ 5.3],
       [ 1.3],
       [ 1.7],
       [-0.9],
       [ 5. ],
       [ 7.6],
       [ 6.1],
       [ 4.3],
       [ 5.9],
       [ 8.5],
       [ 8.8],
       [12.2],
       [10.4],
       [ 5.4],
       [ 5.5],
       [ 6.7],
       [ 6.5],
       [ 6.1],
       [ 4.5],
       [ 2.5],
       [ 3.7],
       [ 5.9],
       [ 3.8],
       [ 4.7],
       [ 5.8],
       [ 4.5]])

In [97]:
from sklearn.linear_model import LinearRegression

In [98]:
model = LinearRegression()

In [99]:
model.fit(np_c_dataset, np_f_dataset)

LinearRegression()

In [100]:
w = model.coef_
b = model.intercept_

In [101]:
w, b

(array([1.]), -2.6645352591003757e-15)

In [104]:
def predict(x):
  print(float(model.predict([[x]])))

In [105]:
import ipywidgets
from ipywidgets import interactive

interactive(predict, x = (0., 100.))

interactive(children=(FloatSlider(value=50.0, description='x'), Output()), _dom_classes=('widget-interact',))